In [3]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x = np.where(arr == 4)
print("\nIndexes where the value is 4:",x)

Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4: (array([3, 5, 6], dtype=int64),)


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print("Original array:",arr)
print("\nIndexes where the values are even:",x) 


Original array: [1 2 3 4 5 6 7 8]

Indexes where the values are even: (array([1, 3, 5, 7], dtype=int64),)


In [10]:
arr = np.array([3, 2, 0, 1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]


In [11]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [12]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [16]:
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)
print("\nVector division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector addition
[12 24 35 48 60]

Vector subtraction
[ 8 16 25 32 40]

Vector multiplication
[ 20  80 150 320 500]

Vector division
[5. 5. 6. 5. 5.]

Vector Dot product
1070
