In [1]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]])
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)
d = np.random.random((2, 2))
print ("\nA random array:\n", d)



An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]

A random array:
 [[0.91160737 0.18982503]
 [0.61902673 0.40991654]]


In [3]:
e = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", e)
arr = np.array([[1, 2, 3, 4],
[5, 2, 4, 2],
[1, 2, 0, 1]])
newarr = arr.reshape(4, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array[4,3]:\n", newarr)
flarr=arr.flatten()
print("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)
#Printing array dimensions (axes)
print("\nNo. of dimensions:", arr.ndim)
print("\nShape of array: ", arr.shape)



A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]

No. of dimensions: 2

Shape of array:  (3, 4)


In [4]:
print("\nSize of array: ", arr.size)
print("\nArray stores elements of type: ", arr.dtype)
newtype=arr.astype('f')
print("\nConverted array elemnets:\n", newtype)
print("Converted array type:", newtype.dtype)


Size of array:  12

Array stores elements of type:  int64

Converted array elemnets:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32
