In [45]:
import numpy as np
a=np.array([[0,4,3,7],[-6,-0.5,9,2],[83,10,7,-1]])
print("Orginal array:\n",a)
print("\nEvery other rows:a[0:2:2]:",a[0:2:2])

Orginal array:
 [[ 0.   4.   3.   7. ]
 [-6.  -0.5  9.   2. ]
 [83.  10.   7.  -1. ]]

Every other rows:a[0:2:2]: [[0. 4. 3. 7.]]


In [46]:
b=a[0:-1]
print(b)

[[ 0.   4.   3.   7. ]
 [-6.  -0.5  9.   2. ]]


In [47]:
temp=a[[0,1,2,2],[3,2,2,1]]
print(temp)

[ 7.  9.  7. 10.]


In [48]:
cond=a>3
temp=a[cond]
print(temp)

[ 4.  7.  9. 83. 10.  7.]


In [49]:
c=np.array([2,87,56,34,1,4,34])
print(c[::3])

[ 2 34 34]


In [50]:
arr1=np.array([2,7,6])
arr2=np.array([15,3,7])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 2  7  6 15  3  7]


In [51]:
arr = np.hstack((arr1, arr2))
print("\horizontal joining:\n",arr)

\horizontal joining:
 [ 2  7  6 15  3  7]


In [52]:
 arr = np.vstack((arr1, arr2))
 print("\nVertical joining:\n",arr)


Vertical joining:
 [[ 2  7  6]
 [15  3  7]]


In [53]:
arr = np.dstack((arr1, arr2))
print("\nDepth joining:\n",arr)



Depth joining:
 [[[ 2 15]
  [ 7  3]
  [ 6  7]]]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2, 3]), array([4, 5, 6])]
